### ISSUE TITLE
Equidistant boxes for the .it_block class

### ISSUE THREAD

**Issue by jacoboyen** [CentralCollege/itservices-wordpress-plugin#5]
We need to rebuild the `.it_block` class so that we can have better equidistant objects on the homepage without wrapping issues. See http://css-tricks.com/equidistant-objects-with-css/ for details.

**Comment by bohrj** [comment]
@jacoboyen Assuming this could be closed, but I'm not able to do so.

**Comment by jacoboyen** [comment]
@bohrj Good call. It doesn't seem like ITS needs this anyway.
